export const countryList = [
    {
        id: "JP",
        name: "Japan",
        img: process.env.PUBLIC_URL + '/assets/japan.jpg',
        visa: "None",
        gover: "None",
        vac: "None",
        hae: "None",
        etc: "None",
    },
    {
        id: "US",
        name: "United States of America",
        img: process.env.PUBLIC_URL + '/assets/us.jpg',
        visa: "None",
        gover: "None",
        vac: "None",
        hae: "None",
        etc: "None",
    },
    {
        id: "AU",
        name: "Australia",
        img: process.env.PUBLIC_URL + '/assets/as.jpg',
        visa: "None",
        gover: "None",
        vac: "None",
        hae: "None",
        etc: "None",
    },
    {
        id: "GB",
        name: "United Kingdom",
        img: process.env.PUBLIC_URL + '/assets/uk.jpg',
        visa: "None",
        gover: "None",
        vac: "None",
        hae: "None",
        etc: "None",
    },
    {
        id: "ES",
        name: "Spain",
        img: process.env.PUBLIC_URL + '/assets/spain.jpg',
        visa: "None",
        gover: "None",
        vac: "None",
        hae: "None",
        etc: "None",
    },
]